language: java
install: true
os: linux
dist: trusty
jdk: openjdk8
stages:
- name: build
- name: snapshot
  if: branch = master AND type IN (push)
- name: release
  if: "(branch = release-0.7.x OR branch = release-0.8.x OR branch = release-0.9.x)
    AND type IN (push)"
jobs:
  include:
  - stage: build
    script: "./gradlew --stacktrace build"
  - stage: release
    script: "./gradlew --stacktrace publishToSonatype"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_2fc2577d012c_key -iv $encrypted_2fc2577d012c_iv
  -in cd/gradle.properties.enc -out cd/gradle.properties -d
- cat cd/gradle.properties >> gradle.properties
- openssl aes-256-cbc -K $encrypted_81c98acad902_key -iv $encrypted_81c98acad902_iv
  -in cd/codesigning.asc.enc -out cd/codesigning.asc -d
- gpg --fast-import cd/codesigning.asc
env:
  global:
  - secure: e2u+GJ1oGZRrEYY83c4XqpcHVBBVWE+79ypwYyD+/J62B7Bb2mcIs1X/b/x4n2kXrltPcXxYfrZjleObIF5i9NPvJrTVMFstUUgMoXEEbr4TbmttsTdYP9LJHajFqI88cX0hXoUdcn1j6S5U5J1CpRLHOr8eMndMBcKJ0GnNpIRH3trmCK5XqonNEojFXoA42u/F9dFNIuHn8GulS0pTYJe7Y4KlGtlXjdJ2TFORFLgurSfmyrMt7Mg+XvNl88UuU96llpzhTO0Ftj3nm8iZbVeHgibmJWEsCRpXj3d/HI8baqUcG9T+DH8Vh+NAuYh3k7hvWJj+IUW2xsAs0WD7EFfAHL+WQufLKsSfqp45U+6uyx7Qh4kkuJHXCqm3NbVeLB17R+8KidZKwSOA8nbWxzYxbPPX44bhcDlnC0TxmflpFwb9hjobklD1q7IHXKRolaqJayUJ4Z307XmGUk6aGGGw7X08nPWCEoAdNLLC0kb/HM4gusMuKJrZGpxt6lsQK+nSF9hZvYDjjwv6iOi6Tq/AJw5/m54i5og4alshqYXvS3Bo9VuXnp9axOTmQut8GW0T0rt9u62Zyr2LKISMy4126L/+qvMuTSOg2ZCEkuP/MxFX+1GvWxSsIR9C4L3YanW9wc+aCKa/LWzwl64y3TFkffK8spN7YRv69JILGCM=
  - secure: Wkx0tXBjDqumXdFSzpkJCUVX28zqpWpWCm9dBDAyUhhwR0B3Fx9V/c0ev7XE++/YN3duORRN5yrY2OpkRcPxUHHAe+HchSM1aVbe7hRCiNFhkXwRaans54JgJxOJPu/JGSVKPOziJLMlvzhg9uJRtdY49cD3OO8vOONK37hcAVvMn/+Uj+47n1D0ZLxVSyoyMmwYOcpm2y1joyRasD+kU9MKDN2ghZ0tVKI+wYjL1emrWzoxnykcQfv+y1sqSs6+zovx4J+KAfYf+Lum54GMKfNBLJR+ztDb4+hPoIRZudFAvoqGtuced7G4s2bXxKzWpTx/c4GQipwWsu7eA2WO4cKHAXlhWGK1Q/xl2lvwgTu2rMqJpMJhNGVrR5Kdz51fMcrKoAh7JKwOX/3kpUub+UcchDfQRYtx6lkkUcge2cahRDXAUlMzdzr8Dz2RPXv7NMAuBzwiPvUTsqD+CjG7AYsIHzHbSiOyhMvM8JYM3uzGBHwt5RVZjS8xAZQW7NYh42lssyajkyKrK0Z9jqN1fM5f/mUVUHetPUc32QvmoQ4WRUbuUutiIbcXuKLZWe0K4XtlbISkulXfggv8NzBanx0H8KRyXJ/qla49jdmseERL7Un3G+XkRPYUW+bLPVMiuiE2SI4+pKA8Dt4hRy0NPTOWdIxpm+X2gZ3io1+H/O8=
